language: cpp

os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.7
    - g++-4.7

before_script:
    - git clone https://github.com/koute/ci-helpers.git

script: bash ./ci-helpers/ci.sh

env:
  matrix:
    - ARCH='i686'
    - ARCH='x86_64'
